name: Check Markdown links

on: 
  push:
    branches:
      - main
  schedule:
  # Run everyday at 9 am
  - cron: "0 9 * * *"

jobs:
  # check all links in the readme.md file
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
