name: Regenerate README.md

on: 
  push:
    branches:
      - source

jobs:
  # use a python environment to run generate.py; commit resulting README.md into repository
  generate-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      # check out 'source' branch
      with:
        ref: source
        fetch-depth: '0'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    # Install yaml
    - name: Install yaml
      run: |
        pip install pyyaml
    - name: Generate README.md
      run: |
        python generate.py
    - name: Commit changes
      run: |
        git checkout main
        mv output.md README.md
        git config --local user.email "github@danielfett.de"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README.md" -a
        git push

